### PR TITLE
Upgrade SDK to Terraform 0.12.2

### PR DESCRIPTION
**Pull request by cyrilgdn**
Replace #83 with a newer version of Terraform 0.12.
I set @tkellen as a co-author as he worked on the original upgrade in #83

Breaking change:
* This remove the default value for `postgresql_role.password`.

### CODE REVIEW

**Comment by pascal-de-ladurantaye** [comment]
Glad to see this issue is getting some love, when can we expect this to be released?

**Comment by cyrilgdn** [comment]
@pascal-de-ladurantaye Hopefully today

**Comment by cyrilgdn** [comment]
@pascal-de-ladurantaye Version 1.0.0 with the Terraform v0.12 compatibility  has been [released](https://github.com/terraform-providers/terraform-provider-postgresql/releases/tag/v1.0.0)

**Comment by pascal-de-ladurantaye** [comment]
@cyrilgdn Thanks a lot!

**Pull request merged**
