### PR TITLE
Alter drop role functionality to work for rds servers

### PR DESCRIPTION
**Pull request by slocke716**
This addresses https://github.com/terraform-providers/terraform-provider-postgresql/issues/36

### CODE REVIEW

**Comment by slocke716** [comment]
Strangely `make testacc` works which is what I was using locally but `make test` fails with
```
FAIL: TestAccPostgresqlRole_Delete (0.00s)
    utils_test.go:71: could not execute query CREATE ROLE tf_tests_role_1586029736021698339 LOGIN ENCRYPTED PASSWORD 'testpwd': pq: no PostgreSQL user name specified in startup packet
```
Is this a configuration thing that I missed?

**Comment by slocke716** [comment]
Older versions of postgres do not let you update the pg_settings view
```
=== RUN   TestAccIsRds_Basic
--- FAIL: TestAccIsRds_Basic (0.42s)
    testing.go:569: Step 0 error: Check failed: Check 1/2 error: could not alter pg_settings: pq: permission denied: "pg_settings" is a system catalog
```
Arguably testing that a select statement works properly to integration test the isRdsSystem function might be frivolous and mocking that in the other tests should suffice for regression.

Please let me know what you think and where I should go with this.

**Comment by cyrilgdn** [comment]
Hi @slocke716 ,

Thanks for opening this PR and for helping on this subject.

I'll take a look as soon as I can.

By re-reading the associated issue, I saw that I mentioned it in #59 , I'll quickly check if we can integrate what you've done with what has been done in #59 in a more generic way.

**Comment by slocke716** [comment]
> Hi @slocke716 ,
> 
> Thanks for opening this PR and for helping on this subject.
> 
> I'll take a look as soon as I can.
> 
> By re-reading the associated issue, I saw that I mentioned it in #59 , I'll quickly check if we can integrate what you've done with what has been done in #59 in a more generic way.

Thanks cyrilgn!
I really hoped to be able to make a generic solution here but couldn't figure one out. Essentially, even on the same postgres version the rds requires the set role and allows the reassign operation in that fashion but vanilla postgres will not allow that user to run a reassign without explicit permissions.
I look forward to seeing your solution.
Please let me know if there is anything I can do to assist. Unfortunately this was my first go at at go :) so I'm not a golang expert.

**Comment by phewitt** [comment]
I need this. :pray:

**Comment by slocke716** [comment]
I've made this pull request which is more generic https://github.com/terraform-providers/terraform-provider-postgresql/pull/135

**Comment by slocke716** [comment]
https://github.com/terraform-providers/terraform-provider-postgresql/pull/135 is a better implementation. Closing this

**Pull request closed without merging**
