### PR TITLE
bump terraform provider to 12

### PR DESCRIPTION
**Pull request by tkellen**
This addresses gh-79. Caveat, I have no idea what I'm doing. I destroyed the go.sum file, updated go.mod with terraform v0.12.0, ran `go mod vendor`, made a tiny edit to fix a panic and confirmed passing tests.

### CODE REVIEW

**Comment by tkellen** [comment]
If you'd like to use this before it is released, clone this branch and run `make`. Then, from the terraform folder you'd like to use this provider from, run the following:
```
mkdir -p .terraform/plugins/linux_amd64
cp $GOPATH/bin/terraform-provider-postgresql ./.terraform/plugins/linux_amd64/terraform-provider-postgresql_v0.4.1
```
*If you're not running linux, be sure to update `linux_amd64` to the correct arch string.*

Ensure your postgresql provider indicates this version should be used:
```
provider "postgresql" {
  ...
  version = "~> 0.4.1"
}
```

*There are ways to configure `.terraformrc` or environment variables to install "third party" providers at some level outside the per-project level, but I found it easiest to test this by copying the plugin directly in.*

**Comment by trawler** [comment]
Would like to see this PR merged. Correct me if I'm wrong, but I believe the tests fail because [this commit](https://github.com/terraform-providers/terraform-provider-postgresql/commit/c44b5b644d81e92f5c852743a372a0d7f4c48aa5#diff-d14b807d9881221269621068e6bd8756) added the PGPASSWORD environment variable, which overrides the expected value in https://github.com/terraform-providers/terraform-provider-postgresql/blob/master/postgresql/resource_postgresql_role_test.go#L41.

**Comment by lawliet89** [comment]
The test failure is really strange. The field is set as `password = ""` but Terraform still uses `DefaultFunc` and reads from the environment. 

Seems like @cyrilgdn has reported this in https://github.com/hashicorp/terraform/issues/21760

**Comment by cyrilgdn** [comment]
@lawliet89 Indeed, it took me quite some time this week to understand and report this issue.

As this issue will probably not be tackled / fixed in the next days, I need to take a decision regarding the release for Terraform 0.12.
The test itself is not really the problem (in the worst case we can temporary remove the "empty string password" case).

So we can:

* Release like that (with a hacked test): The release will contain this bug which impacts people creating a new state with password field set to empty string and a PGPASSWORD environment variable set. First `terraform apply` will set an unexpected password and second one will reset it to the correct value.
* Remove the default value: This breaks a bit the compatibility so maybe we need to change major version.

I'm quite in favor of the second one because I find this default value a bit weird as `PGPASSWORD` is also the default value of the password in the provider settings. So if someone is configuring the provider with  `PGPASSWORD` as admin password, it will set the admin password to all roles created without password..... 

The first one is "safer" and it does probably no impact so many people (and it will probably fixed in future Terraform release)

**Comment by lawliet89** [comment]
I think the second option is better. It seems a bit "surprising" that the environment variable `PGPASSWORD` would affect the password in a resource.

**Comment by cyrilgdn** [comment]
I recreate a new PR #87 to replace this one with a newer release of Terraform 0.12.
(I set @tkellen as a co-author of the upgrade in the new PR to credit his work)

Default value will be removed for `postgresql_role.password`

**Pull request closed without merging**
