### PR TITLE
Use ParseTolerant to allow Major.Minor version numbers that PG 10 uses

### PR DESCRIPTION
**Pull request by tomelliff**
Fixes https://github.com/terraform-providers/terraform-provider-postgresql/issues/30

### CODE REVIEW

**Comment by tomelliff** [comment]
I've ran acceptance tests against a 9.6 Postgres Docker container and a 10.2 Postgres Docker container.

It feels like we should be able to run the acceptance tests in Travis on every PR though because there's no real cost to them unlike the AWS provider acceptance tests (where I have more experience) as we can just run things against a Travis hosted Postgres Docker container.

Would you have any issues with me raising another pull request to add these acceptance tests automatically to the pipeline and some steps about how to test locally?

**Comment by smelchior** [comment]
It would be great if this could be merged, i really want to use the provider with psql 10!

**Comment by jayed** [comment]
It would be great to see this merged.

**Comment by cliveza** [comment]
Merge, do it, you know you want to.

**Comment by sean-** [comment]
Make it so.

**Comment by smelchior** [comment]
Thanks for merging this! When will there be a new release, so i can use the fixed version of the plugin?

**Comment by rsheldon** [comment]
Running into this too - can you please release this?

**Comment by captn3m0** [comment]
Please release this.

**Comment by nomihtaa** [comment]
Voting for this one too, one of our backlog ticket is geting lonely.

**Comment by sean-** [comment]
This was released yesterday as `0.1.2` (thank you @tombuildsstuff!).  Thanks for your patience everyone. Cheers.

**Pull request merged**
